drop extension if exists "pg_net";

create type "public"."plant_category" as enum ('Vegetable', 'Flower', 'Herb', 'Fruit');

create sequence "public"."plants_id_seq";

create sequence "public"."varieties_id_seq";


  create table "public"."plants" (
    "id" integer not null default nextval('public.plants_id_seq'::regclass),
    "plant_name" text not null,
    "scientific_name" character varying(150),
    "weeks_before_frost" integer default 0,
    "sowing_lead_time" integer not null,
    "dev_time_min" integer,
    "dev_time_max" integer,
    "hardiness_level" integer,
    "is_light_germinating" boolean default false,
    "sowing_depth_mm" double precision,
    "plant_spacing_cm" integer,
    "requires_topping" boolean default false,
    "direct_sowing" boolean default false,
    "category" public.plant_category not null default 'Flower'::public.plant_category
      );


alter table "public"."plants" enable row level security;


  create table "public"."seeds" (
    "id" integer generated by default as identity not null,
    "plant_id" integer,
    "name" text not null,
    "variety" text,
    "quantity" integer default 0,
    "expiry_date" date,
    "notes" text,
    "user_id" uuid,
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "variety_id" integer
      );


alter table "public"."seeds" enable row level security;


  create table "public"."sowings" (
    "id" integer generated by default as identity not null,
    "seed_id" integer,
    "sown_date" date not null,
    "status" integer default 0,
    "notes" text,
    "user_id" uuid,
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "quantity" integer
      );


alter table "public"."sowings" enable row level security;


  create table "public"."user_profiles" (
    "id" uuid not null,
    "full_name" text,
    "last_frost_date" date,
    "growing_zone" integer not null default 0,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()),
    "email" text
      );


alter table "public"."user_profiles" enable row level security;


  create table "public"."varieties" (
    "id" integer not null default nextval('public.varieties_id_seq'::regclass),
    "plant_id" integer,
    "variety_name" character varying(100) not null,
    "usage_count" integer default 0
      );


alter table "public"."varieties" enable row level security;

alter sequence "public"."plants_id_seq" owned by "public"."plants"."id";

alter sequence "public"."varieties_id_seq" owned by "public"."varieties"."id";

CREATE UNIQUE INDEX plants_pkey ON public.plants USING btree (id);

CREATE UNIQUE INDEX plants_plant_name_key ON public.plants USING btree (plant_name);

CREATE UNIQUE INDEX seeds_pkey ON public.seeds USING btree (id);

CREATE UNIQUE INDEX sowings_pkey ON public.sowings USING btree (id);

CREATE UNIQUE INDEX user_profiles_pkey ON public.user_profiles USING btree (id);

CREATE UNIQUE INDEX varieties_pkey ON public.varieties USING btree (id);

alter table "public"."plants" add constraint "plants_pkey" PRIMARY KEY using index "plants_pkey";

alter table "public"."seeds" add constraint "seeds_pkey" PRIMARY KEY using index "seeds_pkey";

alter table "public"."sowings" add constraint "sowings_pkey" PRIMARY KEY using index "sowings_pkey";

alter table "public"."user_profiles" add constraint "user_profiles_pkey" PRIMARY KEY using index "user_profiles_pkey";

alter table "public"."varieties" add constraint "varieties_pkey" PRIMARY KEY using index "varieties_pkey";

alter table "public"."plants" add constraint "plants_plant_name_key" UNIQUE using index "plants_plant_name_key";

alter table "public"."seeds" add constraint "seeds_plant_id_fkey" FOREIGN KEY (plant_id) REFERENCES public.plants(id) not valid;

alter table "public"."seeds" validate constraint "seeds_plant_id_fkey";

alter table "public"."seeds" add constraint "seeds_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."seeds" validate constraint "seeds_user_id_fkey";

alter table "public"."seeds" add constraint "seeds_variety_id_fkey" FOREIGN KEY (variety_id) REFERENCES public.varieties(id) not valid;

alter table "public"."seeds" validate constraint "seeds_variety_id_fkey";

alter table "public"."sowings" add constraint "sowings_seed_id_fkey" FOREIGN KEY (seed_id) REFERENCES public.seeds(id) ON DELETE CASCADE not valid;

alter table "public"."sowings" validate constraint "sowings_seed_id_fkey";

alter table "public"."sowings" add constraint "sowings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."sowings" validate constraint "sowings_user_id_fkey";

alter table "public"."user_profiles" add constraint "user_profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_id_fkey";

alter table "public"."varieties" add constraint "varieties_plant_id_fkey" FOREIGN KEY (plant_id) REFERENCES public.plants(id) not valid;

alter table "public"."varieties" validate constraint "varieties_plant_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
  -- Lägg till "growing_zone" i kolumnlistan och värdet 0 i VALUES
  INSERT INTO public."user_profiles" (
    id, 
    "full_name", 
    "email", 
    "growing_zone", -- Ny kolumn här
    "updated_at"
  )
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.email, 
    0,              -- Sätter standardvärdet till 0 här
    NOW()
  );
  RETURN new;
END;$function$
;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

create or replace view "public"."v_user_inventory" as  SELECT s.id,
    s.user_id,
    s.name,
    s.quantity,
    s.expiry_date,
    s.notes,
    s.plant_id,
    s.variety_id,
    p.plant_name,
    v.variety_name
   FROM ((public.seeds s
     LEFT JOIN public.plants p ON ((s.plant_id = p.id)))
     LEFT JOIN public.varieties v ON ((s.variety_id = v.id)));


create or replace view "public"."v_user_sowings" as  SELECT sw.id,
    sw.user_id,
    sw.sown_date,
    sw.status,
    sw.notes,
    sw.quantity,
    sw.seed_id,
    s.name AS seed_name,
    p.plant_name,
    v.variety_name,
    p.sowing_depth_mm,
    p.is_light_germinating,
    p.requires_topping
   FROM (((public.sowings sw
     JOIN public.seeds s ON ((sw.seed_id = s.id)))
     LEFT JOIN public.plants p ON ((s.plant_id = p.id)))
     LEFT JOIN public.varieties v ON ((s.variety_id = v.id)));


grant delete on table "public"."plants" to "anon";

grant insert on table "public"."plants" to "anon";

grant references on table "public"."plants" to "anon";

grant select on table "public"."plants" to "anon";

grant trigger on table "public"."plants" to "anon";

grant truncate on table "public"."plants" to "anon";

grant update on table "public"."plants" to "anon";

grant delete on table "public"."plants" to "authenticated";

grant insert on table "public"."plants" to "authenticated";

grant references on table "public"."plants" to "authenticated";

grant select on table "public"."plants" to "authenticated";

grant trigger on table "public"."plants" to "authenticated";

grant truncate on table "public"."plants" to "authenticated";

grant update on table "public"."plants" to "authenticated";

grant delete on table "public"."plants" to "service_role";

grant insert on table "public"."plants" to "service_role";

grant references on table "public"."plants" to "service_role";

grant select on table "public"."plants" to "service_role";

grant trigger on table "public"."plants" to "service_role";

grant truncate on table "public"."plants" to "service_role";

grant update on table "public"."plants" to "service_role";

grant delete on table "public"."seeds" to "anon";

grant insert on table "public"."seeds" to "anon";

grant references on table "public"."seeds" to "anon";

grant select on table "public"."seeds" to "anon";

grant trigger on table "public"."seeds" to "anon";

grant truncate on table "public"."seeds" to "anon";

grant update on table "public"."seeds" to "anon";

grant delete on table "public"."seeds" to "authenticated";

grant insert on table "public"."seeds" to "authenticated";

grant references on table "public"."seeds" to "authenticated";

grant select on table "public"."seeds" to "authenticated";

grant trigger on table "public"."seeds" to "authenticated";

grant truncate on table "public"."seeds" to "authenticated";

grant update on table "public"."seeds" to "authenticated";

grant delete on table "public"."seeds" to "service_role";

grant insert on table "public"."seeds" to "service_role";

grant references on table "public"."seeds" to "service_role";

grant select on table "public"."seeds" to "service_role";

grant trigger on table "public"."seeds" to "service_role";

grant truncate on table "public"."seeds" to "service_role";

grant update on table "public"."seeds" to "service_role";

grant delete on table "public"."sowings" to "anon";

grant insert on table "public"."sowings" to "anon";

grant references on table "public"."sowings" to "anon";

grant select on table "public"."sowings" to "anon";

grant trigger on table "public"."sowings" to "anon";

grant truncate on table "public"."sowings" to "anon";

grant update on table "public"."sowings" to "anon";

grant delete on table "public"."sowings" to "authenticated";

grant insert on table "public"."sowings" to "authenticated";

grant references on table "public"."sowings" to "authenticated";

grant select on table "public"."sowings" to "authenticated";

grant trigger on table "public"."sowings" to "authenticated";

grant truncate on table "public"."sowings" to "authenticated";

grant update on table "public"."sowings" to "authenticated";

grant delete on table "public"."sowings" to "service_role";

grant insert on table "public"."sowings" to "service_role";

grant references on table "public"."sowings" to "service_role";

grant select on table "public"."sowings" to "service_role";

grant trigger on table "public"."sowings" to "service_role";

grant truncate on table "public"."sowings" to "service_role";

grant update on table "public"."sowings" to "service_role";

grant delete on table "public"."user_profiles" to "anon";

grant insert on table "public"."user_profiles" to "anon";

grant references on table "public"."user_profiles" to "anon";

grant select on table "public"."user_profiles" to "anon";

grant trigger on table "public"."user_profiles" to "anon";

grant truncate on table "public"."user_profiles" to "anon";

grant update on table "public"."user_profiles" to "anon";

grant delete on table "public"."user_profiles" to "authenticated";

grant insert on table "public"."user_profiles" to "authenticated";

grant references on table "public"."user_profiles" to "authenticated";

grant select on table "public"."user_profiles" to "authenticated";

grant trigger on table "public"."user_profiles" to "authenticated";

grant truncate on table "public"."user_profiles" to "authenticated";

grant update on table "public"."user_profiles" to "authenticated";

grant delete on table "public"."user_profiles" to "service_role";

grant insert on table "public"."user_profiles" to "service_role";

grant references on table "public"."user_profiles" to "service_role";

grant select on table "public"."user_profiles" to "service_role";

grant trigger on table "public"."user_profiles" to "service_role";

grant truncate on table "public"."user_profiles" to "service_role";

grant update on table "public"."user_profiles" to "service_role";

grant delete on table "public"."varieties" to "anon";

grant insert on table "public"."varieties" to "anon";

grant references on table "public"."varieties" to "anon";

grant select on table "public"."varieties" to "anon";

grant trigger on table "public"."varieties" to "anon";

grant truncate on table "public"."varieties" to "anon";

grant update on table "public"."varieties" to "anon";

grant delete on table "public"."varieties" to "authenticated";

grant insert on table "public"."varieties" to "authenticated";

grant references on table "public"."varieties" to "authenticated";

grant select on table "public"."varieties" to "authenticated";

grant trigger on table "public"."varieties" to "authenticated";

grant truncate on table "public"."varieties" to "authenticated";

grant update on table "public"."varieties" to "authenticated";

grant delete on table "public"."varieties" to "service_role";

grant insert on table "public"."varieties" to "service_role";

grant references on table "public"."varieties" to "service_role";

grant select on table "public"."varieties" to "service_role";

grant trigger on table "public"."varieties" to "service_role";

grant truncate on table "public"."varieties" to "service_role";

grant update on table "public"."varieties" to "service_role";


  create policy "Allow read access for authenticated users"
  on "public"."plants"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Users can manage their own seeds"
  on "public"."seeds"
  as permissive
  for all
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Users can manage their own sowings"
  on "public"."sowings"
  as permissive
  for all
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Users can manage own profile"
  on "public"."user_profiles"
  as permissive
  for all
  to authenticated
using ((auth.uid() = id))
with check ((auth.uid() = id));



  create policy "Användare kan se sorter"
  on "public"."varieties"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Användare kan skapa nya sorter"
  on "public"."varieties"
  as permissive
  for insert
  to public
with check ((auth.role() = 'authenticated'::text));


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


